version: '3.7'

services:
  app:
    build:
      context: .
    container_name: library_app
    env_file:
      - .env.dist
    depends_on:
      - db
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && python -m init_db && python -m main"
    networks:
      - app-network
  db:
    image: postgres:17.2-alpine
    container_name: library_db
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=super_admin
      - POSTGRES_PASSWORD=super_pass12345
      - POSTGRES_DB=library_management
    networks:
      - app-network
networks:
  app-network: